set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mhz]
set_property PACKAGE_PIN H2 [get_ports clk_25mhz]
set_property PACKAGE_PIN A4 [get_ports {gpio_led[3]}]
set_property PACKAGE_PIN B5 [get_ports {gpio_led[2]}]
set_property PACKAGE_PIN A5 [get_ports {gpio_led[1]}]
set_property PACKAGE_PIN B6 [get_ports {gpio_led[0]}]
create_clock -period 40.000 -name clk_25mhz -waveform {0.000 20.000} [get_ports clk_25mhz]

set_property IOSTANDARD LVCMOS33 [get_ports {portA_rx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portA_rx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portA_rx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portA_rx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portA_tx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portA_tx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portA_tx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portA_tx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portB_rx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portB_rx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portB_rx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portB_rx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portB_tx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portB_tx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portB_tx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {portB_tx_data[0]}]
set_property PACKAGE_PIN C12 [get_ports {portA_rx_data[3]}]
set_property PACKAGE_PIN A12 [get_ports {portA_rx_data[2]}]
set_property PACKAGE_PIN A13 [get_ports {portA_rx_data[1]}]
set_property PACKAGE_PIN B13 [get_ports {portA_rx_data[0]}]
set_property PACKAGE_PIN E13 [get_ports {portA_tx_data[3]}]
set_property PACKAGE_PIN E12 [get_ports {portA_tx_data[2]}]
set_property PACKAGE_PIN J13 [get_ports {portB_rx_data[3]}]
set_property PACKAGE_PIN L14 [get_ports {portB_rx_data[2]}]
set_property PACKAGE_PIN L13 [get_ports {portB_rx_data[1]}]
set_property PACKAGE_PIN M14 [get_ports {portB_rx_data[0]}]
set_property PACKAGE_PIN H14 [get_ports {portB_tx_data[3]}]
set_property PACKAGE_PIN H13 [get_ports {portB_tx_data[2]}]
set_property PACKAGE_PIN E11 [get_ports {portA_tx_data[1]}]
set_property PACKAGE_PIN D12 [get_ports {portA_tx_data[0]}]
set_property PACKAGE_PIN G14 [get_ports {portB_tx_data[1]}]
set_property PACKAGE_PIN F14 [get_ports {portB_tx_data[0]}]
set_property PACKAGE_PIN D14 [get_ports portA_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports portA_rst_n]
set_property PACKAGE_PIN G11 [get_ports portA_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports portA_rx_clk]
set_property PACKAGE_PIN B14 [get_ports portA_rx_en]
set_property IOSTANDARD LVCMOS33 [get_ports portA_rx_en]
set_property PACKAGE_PIN F12 [get_ports portA_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports portA_tx_clk]
set_property PACKAGE_PIN F13 [get_ports portA_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports portA_tx_en]
set_property PACKAGE_PIN P12 [get_ports portB_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports portB_rst_n]
set_property PACKAGE_PIN H11 [get_ports portB_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports portB_rx_clk]
set_property PACKAGE_PIN M13 [get_ports portB_rx_en]
set_property IOSTANDARD LVCMOS33 [get_ports portB_rx_en]
set_property PACKAGE_PIN H12 [get_ports portB_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports portB_tx_clk]
set_property PACKAGE_PIN J14 [get_ports portB_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports portB_tx_en]
create_clock -period 8.000 -name portA_rx_clk -waveform {0.000 4.000} [get_ports portA_rx_clk]
create_clock -period 8.000 -name portB_rx_clk [get_ports portB_rx_clk]
create_generated_clock -name clk_system -source [get_pins clkgen/pll/mmcm/CLKIN1] -master_clock [get_clocks clk_25mhz] [get_pins clkgen/pll/mmcm/CLKOUT0]
create_generated_clock -name clk_125mhz -source [get_pins clkgen/pll/mmcm/CLKIN1] -master_clock [get_clocks clk_25mhz] [get_pins clkgen/pll/mmcm/CLKOUT1]
create_generated_clock -name clk_250mhz -source [get_pins clkgen/pll/mmcm/CLKIN1] -master_clock [get_clocks clk_25mhz] [get_pins clkgen/pll/mmcm/CLKOUT2]
create_generated_clock -name clk_200mhz -source [get_pins clkgen/pll/mmcm/CLKIN1] -master_clock [get_clocks clk_25mhz] [get_pins clkgen/pll/mmcm/CLKOUT3]
create_generated_clock -name clk_50mhz -source [get_pins clkgen/pll/mmcm/CLKIN1] -master_clock [get_clocks clk_25mhz] [get_pins clkgen/pll/mmcm/CLKOUT4]

set_clock_groups -asynchronous -group [get_clocks portA_rx_clk] -group [get_clocks clk_125mhz]
set_clock_groups -asynchronous -group [get_clocks portB_rx_clk] -group [get_clocks clk_125mhz]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz] -group [get_clocks portA_rx_clk]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz] -group [get_clocks portB_rx_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {monA_rx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monA_rx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monA_rx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monA_rx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monA_tx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monA_tx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monA_tx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monA_tx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monB_rx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monB_rx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monB_rx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monB_rx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monB_tx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monB_tx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monB_tx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {monB_tx_data[0]}]
set_property PACKAGE_PIN P3 [get_ports {monA_rx_data[3]}]
set_property PACKAGE_PIN P2 [get_ports {monA_rx_data[2]}]
set_property PACKAGE_PIN N1 [get_ports {monA_rx_data[1]}]
set_property PACKAGE_PIN M2 [get_ports {monA_rx_data[0]}]
set_property PACKAGE_PIN P5 [get_ports {monA_tx_data[3]}]
set_property PACKAGE_PIN L3 [get_ports {monA_tx_data[2]}]
set_property PACKAGE_PIN M3 [get_ports {monA_tx_data[1]}]
set_property PACKAGE_PIN M4 [get_ports {monA_tx_data[0]}]
set_property PACKAGE_PIN D1 [get_ports {monB_rx_data[3]}]
set_property PACKAGE_PIN D2 [get_ports {monB_rx_data[2]}]
set_property PACKAGE_PIN C1 [get_ports {monB_rx_data[1]}]
set_property PACKAGE_PIN B1 [get_ports {monB_rx_data[0]}]
set_property PACKAGE_PIN F1 [get_ports {monB_tx_data[3]}]
set_property PACKAGE_PIN G1 [get_ports {monB_tx_data[2]}]
set_property PACKAGE_PIN J2 [get_ports {monB_tx_data[1]}]
set_property PACKAGE_PIN J1 [get_ports {monB_tx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports monA_rst_n]
set_property PACKAGE_PIN J3 [get_ports monA_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports monA_rx_clk]
set_property PACKAGE_PIN H4 [get_ports monA_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports monA_rx_en]
set_property PACKAGE_PIN M1 [get_ports monA_rx_en]
set_property IOSTANDARD LVCMOS33 [get_ports monA_tx_clk]
set_property PACKAGE_PIN P4 [get_ports monA_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports monA_tx_en]
set_property PACKAGE_PIN N4 [get_ports monA_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports monB_rst_n]
set_property PACKAGE_PIN C3 [get_ports monB_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports monB_rx_en]
set_property IOSTANDARD LVCMOS33 [get_ports monB_rx_clk]
set_property PACKAGE_PIN G4 [get_ports monB_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports monB_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports monB_tx_clk]
set_property PACKAGE_PIN B2 [get_ports monB_rx_en]
set_property PACKAGE_PIN F2 [get_ports monB_tx_clk]
set_property PACKAGE_PIN E2 [get_ports monB_tx_en]

create_clock -period 8.000 -name monA_rx_clk -waveform {0.000 4.000} [get_ports monA_rx_clk]
create_clock -period 8.000 -name monB_rx_clk [get_ports monB_rx_clk]
set_clock_groups -asynchronous -group [get_clocks monA_rx_clk] -group [get_clocks clk_125mhz]
set_clock_groups -asynchronous -group [get_clocks monB_rx_clk] -group [get_clocks clk_125mhz]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz] -group [get_clocks monA_rx_clk]
set_clock_groups -asynchronous -group [get_clocks clk_125mhz] -group [get_clocks monB_rx_clk]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {qspi_dq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {qspi_dq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {qspi_dq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {qspi_dq[0]}]
set_property PACKAGE_PIN P11 [get_ports {qspi_dq[3]}]
set_property PACKAGE_PIN M12 [get_ports {qspi_dq[2]}]
set_property PACKAGE_PIN J12 [get_ports {qspi_dq[1]}]
set_property PACKAGE_PIN N10 [get_ports {qspi_dq[0]}]
set_property PACKAGE_PIN K12 [get_ports mcu_irq]
set_property IOSTANDARD LVCMOS33 [get_ports mcu_irq]
set_property PACKAGE_PIN M11 [get_ports qspi_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_cs_n]
set_property PACKAGE_PIN P10 [get_ports qspi_sck]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_sck]

set_property IOSTANDARD LVCMOS33 [get_ports {mdc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdc[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mdio[0]}]
set_property PACKAGE_PIN C14 [get_ports {mdc[0]}]
set_property PACKAGE_PIN N14 [get_ports {mdc[1]}]
set_property PACKAGE_PIN D13 [get_ports {mdio[0]}]
set_property PACKAGE_PIN P13 [get_ports {mdio[1]}]
set_property PACKAGE_PIN L1 [get_ports {mdio[2]}]
set_property PACKAGE_PIN A3 [get_ports {mdio[3]}]
set_property PACKAGE_PIN L2 [get_ports {mdc[2]}]
set_property PACKAGE_PIN A2 [get_ports {mdc[3]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_125mhz]
